apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
  annotations:
    webhookconverted: Webhook converted From oda.tmforum.org/v1beta3 to oda.tmforum.org/v1
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    version: {{.Values.component.version}}
    description: >-
      Simple Product Inventory ODA-Component from Open-API reference
      implementation.
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: {{.Values.component.publicationDate}}
    status: specified
    maintainers:
      - name: Dominic Oyeniran
        email: dominic.oyeniran@vodafone.com
    owners:
      - name: Dominic Oyeniran
        email: dominic.oyeniran@vodafone.com
  coreFunction:
    exposedAPIs:
      - name: productinventorymanagement
        specification:
          - url: >-
              https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF637-ProductInventory-v4.0.0.swagger.json
        implementation: {{.Release.Name}}-productinventoryapi
        apiType: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productInventory/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productInventory/v4/docs
        port: 8080
        gatewayConfiguration: {}
    dependentAPIs:
      - name: party
        apiType: openapi
        specification:
          - url: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction:
    exposedAPIs: []
    dependentAPIs: []
  securityFunction:
    canvasSystemRole: {{.Values.security.controllerRole}}
    exposedAPIs:
      - name: partyrole
        specification:
          - url: >-
              https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: {{.Release.Name}}-partyroleapi
        apiType: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
        port: 8080
        gatewayConfiguration: {}
    
  

